baseURL = "https://example.com/"
languageCode = "en-gb"
title = "The Riley Zone"
theme = "hugo-theme-prav"

pygmentsCodeFences = "true"
pygmentsStyle = "perldoc"

# If you want to track using GA or use disqus for comments, uncomment the 
# following and add the correct values
#googleanalytics = ""
#disqusShortname = ""

# The settings below are used throughout the theme.
# Please update!
[params]
  title = "The Riley Zone"
  tagline = "maclunky"
  author = "Riley"
  authorImgPath = "/img/author.png"
  authorBlurb = "It me"

# If you do not want a social icon, just comment it out
# Please update the example values!
[params.social]
  email = "mailto:example@example.com"
  facebook = "https://www.facebook.com/example"
  twitter = "http://twitter.com/example"
  medium = "https://www.medium.com/@example"
  github = "https://github.com/hnmns"
  linkedin = "https://www.linkedin.com/in/riley-kouns-6470aa193/"
  mastodon = "https://mstdn.social/example"


# Set unsafe mode to allow markdownify to work with goldmark
#Â This is important. Please do not delete. It is used to re-render markdown
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true